apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: Front End Component Service
  name: Front End Component Service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Front End Component Service
  template:
    metadata:
      labels:
        app: Front End Component Service
    spec:
      containers:
        - image: 'cremerfc/appdirect:10'
          name: appdirect
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: Front End Component Service-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: Front End Component Service
  type: LoadBalancer
